//! 주식선물 실시간호가 — WebSocket /tryitout/H0ZFASP0
//!
//! 스펙: .agent/specs/futureoption_domestic__realtime__h0zfasp0.md
//! 실시간 WebSocket API. 모의투자 미지원.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0ZFASP0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub futs_shrn_iscd: String,
    pub bsop_hour: String,
    pub askp1: String,
    pub askp2: String,
    pub askp3: String,
    pub askp4: String,
    pub askp5: String,
    pub askp6: String,
    pub askp7: String,
    pub askp8: String,
    pub askp9: String,
    pub askp10: String,
    pub bidp1: String,
    pub bidp2: String,
    pub bidp3: String,
    pub bidp4: String,
    pub bidp5: String,
    pub bidp6: String,
    pub bidp7: String,
    pub bidp8: String,
    pub bidp9: String,
    pub bidp10: String,
    pub askp_csnu1: String,
    pub askp_csnu2: String,
    pub askp_csnu3: String,
    pub askp_csnu4: String,
    pub askp_csnu5: String,
    pub askp_csnu6: String,
    pub askp_csnu7: String,
    pub askp_csnu8: String,
    pub askp_csnu9: String,
    pub askp_csnu10: String,
    pub bidp_csnu1: String,
    pub bidp_csnu2: String,
    pub bidp_csnu3: String,
    pub bidp_csnu4: String,
    pub bidp_csnu5: String,
    pub bidp_csnu6: String,
    pub bidp_csnu7: String,
    pub bidp_csnu8: String,
    pub bidp_csnu9: String,
    pub bidp_csnu10: String,
    pub askp_rsqn1: String,
    pub askp_rsqn2: String,
    pub askp_rsqn3: String,
    pub askp_rsqn4: String,
    pub askp_rsqn5: String,
    pub askp_rsqn6: String,
    pub askp_rsqn7: String,
    pub askp_rsqn8: String,
    pub askp_rsqn9: String,
    pub askp_rsqn10: String,
    pub bidp_rsqn1: String,
    pub bidp_rsqn2: String,
    pub bidp_rsqn3: String,
    pub bidp_rsqn4: String,
    pub bidp_rsqn5: String,
    pub bidp_rsqn6: String,
    pub bidp_rsqn7: String,
    pub bidp_rsqn8: String,
    pub bidp_rsqn9: String,
    pub bidp_rsqn10: String,
    pub total_askp_csnu: String,
    pub total_bidp_csnu: String,
    pub total_askp_rsqn: String,
    pub total_bidp_rsqn: String,
    pub total_askp_rsqn_icdc: String,
    pub total_bidp_rsqn_icdc: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 68 {
        return Err(anyhow!("필드 수 부족: {} < 68", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        futs_shrn_iscd: g(0),
        bsop_hour: g(1),
        askp1: g(2),
        askp2: g(3),
        askp3: g(4),
        askp4: g(5),
        askp5: g(6),
        askp6: g(7),
        askp7: g(8),
        askp8: g(9),
        askp9: g(10),
        askp10: g(11),
        bidp1: g(12),
        bidp2: g(13),
        bidp3: g(14),
        bidp4: g(15),
        bidp5: g(16),
        bidp6: g(17),
        bidp7: g(18),
        bidp8: g(19),
        bidp9: g(20),
        bidp10: g(21),
        askp_csnu1: g(22),
        askp_csnu2: g(23),
        askp_csnu3: g(24),
        askp_csnu4: g(25),
        askp_csnu5: g(26),
        askp_csnu6: g(27),
        askp_csnu7: g(28),
        askp_csnu8: g(29),
        askp_csnu9: g(30),
        askp_csnu10: g(31),
        bidp_csnu1: g(32),
        bidp_csnu2: g(33),
        bidp_csnu3: g(34),
        bidp_csnu4: g(35),
        bidp_csnu5: g(36),
        bidp_csnu6: g(37),
        bidp_csnu7: g(38),
        bidp_csnu8: g(39),
        bidp_csnu9: g(40),
        bidp_csnu10: g(41),
        askp_rsqn1: g(42),
        askp_rsqn2: g(43),
        askp_rsqn3: g(44),
        askp_rsqn4: g(45),
        askp_rsqn5: g(46),
        askp_rsqn6: g(47),
        askp_rsqn7: g(48),
        askp_rsqn8: g(49),
        askp_rsqn9: g(50),
        askp_rsqn10: g(51),
        bidp_rsqn1: g(52),
        bidp_rsqn2: g(53),
        bidp_rsqn3: g(54),
        bidp_rsqn4: g(55),
        bidp_rsqn5: g(56),
        bidp_rsqn6: g(57),
        bidp_rsqn7: g(58),
        bidp_rsqn8: g(59),
        bidp_rsqn9: g(60),
        bidp_rsqn10: g(61),
        total_askp_csnu: g(62),
        total_bidp_csnu: g(63),
        total_askp_rsqn: g(64),
        total_bidp_rsqn: g(65),
        total_askp_rsqn_icdc: g(66),
        total_bidp_rsqn_icdc: g(67),
    })
}
