//! 주식옵션 실시간호가 — WebSocket /tryitout/H0ZOASP0
//!
//! 스펙: .agent/specs/futureoption_domestic__realtime__h0zoasp0.md
//! 실시간 WebSocket API. 모의투자 미지원.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0ZOASP0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub optn_shrn_iscd: String,
    pub bsop_hour: String,
    pub optn_askp1: String,
    pub optn_askp2: String,
    pub optn_askp3: String,
    pub optn_askp4: String,
    pub optn_askp5: String,
    pub optn_bidp1: String,
    pub optn_bidp2: String,
    pub optn_bidp3: String,
    pub optn_bidp4: String,
    pub optn_bidp5: String,
    pub askp_csnu1: String,
    pub askp_csnu2: String,
    pub askp_csnu3: String,
    pub askp_csnu4: String,
    pub askp_csnu5: String,
    pub bidp_csnu1: String,
    pub bidp_csnu2: String,
    pub bidp_csnu3: String,
    pub bidp_csnu4: String,
    pub bidp_csnu5: String,
    pub askp_rsqn1: String,
    pub askp_rsqn2: String,
    pub askp_rsqn3: String,
    pub askp_rsqn4: String,
    pub askp_rsqn5: String,
    pub bidp_rsqn1: String,
    pub bidp_rsqn2: String,
    pub bidp_rsqn3: String,
    pub bidp_rsqn4: String,
    pub bidp_rsqn5: String,
    pub total_askp_csnu: String,
    pub total_bidp_csnu: String,
    pub total_askp_rsqn: String,
    pub total_bidp_rsqn: String,
    pub total_askp_rsqn_icdc: String,
    pub total_bidp_rsqn_icdc: String,
    pub optn_askp6: String,
    pub optn_askp7: String,
    pub optn_askp8: String,
    pub optn_askp9: String,
    pub optn_askp10: String,
    pub optn_bidp6: String,
    pub optn_bidp7: String,
    pub optn_bidp8: String,
    pub optn_bidp9: String,
    pub optn_bidp10: String,
    pub askp_csnu6: String,
    pub askp_csnu7: String,
    pub askp_csnu8: String,
    pub askp_csnu9: String,
    pub askp_csnu10: String,
    pub bidp_csnu6: String,
    pub bidp_csnu7: String,
    pub bidp_csnu8: String,
    pub bidp_csnu9: String,
    pub bidp_csnu10: String,
    pub askp_rsqn6: String,
    pub askp_rsqn7: String,
    pub askp_rsqn8: String,
    pub askp_rsqn9: String,
    pub askp_rsqn10: String,
    pub bidp_rsqn6: String,
    pub bidp_rsqn7: String,
    pub bidp_rsqn8: String,
    pub bidp_rsqn9: String,
    pub bidp_rsqn10: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 68 {
        return Err(anyhow!("필드 수 부족: {} < 68", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        optn_shrn_iscd: g(0),
        bsop_hour: g(1),
        optn_askp1: g(2),
        optn_askp2: g(3),
        optn_askp3: g(4),
        optn_askp4: g(5),
        optn_askp5: g(6),
        optn_bidp1: g(7),
        optn_bidp2: g(8),
        optn_bidp3: g(9),
        optn_bidp4: g(10),
        optn_bidp5: g(11),
        askp_csnu1: g(12),
        askp_csnu2: g(13),
        askp_csnu3: g(14),
        askp_csnu4: g(15),
        askp_csnu5: g(16),
        bidp_csnu1: g(17),
        bidp_csnu2: g(18),
        bidp_csnu3: g(19),
        bidp_csnu4: g(20),
        bidp_csnu5: g(21),
        askp_rsqn1: g(22),
        askp_rsqn2: g(23),
        askp_rsqn3: g(24),
        askp_rsqn4: g(25),
        askp_rsqn5: g(26),
        bidp_rsqn1: g(27),
        bidp_rsqn2: g(28),
        bidp_rsqn3: g(29),
        bidp_rsqn4: g(30),
        bidp_rsqn5: g(31),
        total_askp_csnu: g(32),
        total_bidp_csnu: g(33),
        total_askp_rsqn: g(34),
        total_bidp_rsqn: g(35),
        total_askp_rsqn_icdc: g(36),
        total_bidp_rsqn_icdc: g(37),
        optn_askp6: g(38),
        optn_askp7: g(39),
        optn_askp8: g(40),
        optn_askp9: g(41),
        optn_askp10: g(42),
        optn_bidp6: g(43),
        optn_bidp7: g(44),
        optn_bidp8: g(45),
        optn_bidp9: g(46),
        optn_bidp10: g(47),
        askp_csnu6: g(48),
        askp_csnu7: g(49),
        askp_csnu8: g(50),
        askp_csnu9: g(51),
        askp_csnu10: g(52),
        bidp_csnu6: g(53),
        bidp_csnu7: g(54),
        bidp_csnu8: g(55),
        bidp_csnu9: g(56),
        bidp_csnu10: g(57),
        askp_rsqn6: g(58),
        askp_rsqn7: g(59),
        askp_rsqn8: g(60),
        askp_rsqn9: g(61),
        askp_rsqn10: g(62),
        bidp_rsqn6: g(63),
        bidp_rsqn7: g(64),
        bidp_rsqn8: g(65),
        bidp_rsqn9: g(66),
        bidp_rsqn10: g(67),
    })
}
