//! 국내주식 실시간호가 (NXT) — WebSocket /tryitout/H0NXASP0
//!
//! 스펙: .agent/specs/domestic_stock__realtime__h0nxasp0.md
//! 실시간 WebSocket API. 모의투자 미지원. NXT 시장 호가.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0NXASP0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub mksc_shrn_iscd: String,
    pub bsop_hour: String,
    pub hour_cls_code: String,
    pub askp1: String,
    pub askp2: String,
    pub askp3: String,
    pub askp4: String,
    pub askp5: String,
    pub askp6: String,
    pub askp7: String,
    pub askp8: String,
    pub askp9: String,
    pub askp10: String,
    pub bidp1: String,
    pub bidp2: String,
    pub bidp3: String,
    pub bidp4: String,
    pub bidp5: String,
    pub bidp6: String,
    pub bidp7: String,
    pub bidp8: String,
    pub bidp9: String,
    pub bidp10: String,
    pub askp_rsqn1: String,
    pub askp_rsqn2: String,
    pub askp_rsqn3: String,
    pub askp_rsqn4: String,
    pub askp_rsqn5: String,
    pub askp_rsqn6: String,
    pub askp_rsqn7: String,
    pub askp_rsqn8: String,
    pub askp_rsqn9: String,
    pub askp_rsqn10: String,
    pub bidp_rsqn1: String,
    pub bidp_rsqn2: String,
    pub bidp_rsqn3: String,
    pub bidp_rsqn4: String,
    pub bidp_rsqn5: String,
    pub bidp_rsqn6: String,
    pub bidp_rsqn7: String,
    pub bidp_rsqn8: String,
    pub bidp_rsqn9: String,
    pub bidp_rsqn10: String,
    pub total_askp_rsqn: String,
    pub total_bidp_rsqn: String,
    pub ovtm_total_askp_rsqn: String,
    pub ovtm_total_bidp_rsqn: String,
    pub antc_cnpr: String,
    pub antc_cnqn: String,
    pub antc_vol: String,
    pub antc_cntg_vrss: String,
    pub antc_cntg_vrss_sign: String,
    pub antc_cntg_prdy_ctrt: String,
    pub acml_vol: String,
    pub total_askp_rsqn_icdc: String,
    pub total_bidp_rsqn_icdc: String,
    pub ovtm_total_askp_icdc: String,
    pub ovtm_total_bidp_icdc: String,
    pub stck_deal_cls_code: String,
    pub kmid_prc: String,
    pub kmid_total_rsqn: String,
    pub kmid_cls_code: String,
    pub nmid_prc: String,
    pub nmid_total_rsqn: String,
    pub nmid_cls_code: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 65 {
        return Err(anyhow!("필드 수 부족: {} < 65", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        mksc_shrn_iscd: g(0),
        bsop_hour: g(1),
        hour_cls_code: g(2),
        askp1: g(3),
        askp2: g(4),
        askp3: g(5),
        askp4: g(6),
        askp5: g(7),
        askp6: g(8),
        askp7: g(9),
        askp8: g(10),
        askp9: g(11),
        askp10: g(12),
        bidp1: g(13),
        bidp2: g(14),
        bidp3: g(15),
        bidp4: g(16),
        bidp5: g(17),
        bidp6: g(18),
        bidp7: g(19),
        bidp8: g(20),
        bidp9: g(21),
        bidp10: g(22),
        askp_rsqn1: g(23),
        askp_rsqn2: g(24),
        askp_rsqn3: g(25),
        askp_rsqn4: g(26),
        askp_rsqn5: g(27),
        askp_rsqn6: g(28),
        askp_rsqn7: g(29),
        askp_rsqn8: g(30),
        askp_rsqn9: g(31),
        askp_rsqn10: g(32),
        bidp_rsqn1: g(33),
        bidp_rsqn2: g(34),
        bidp_rsqn3: g(35),
        bidp_rsqn4: g(36),
        bidp_rsqn5: g(37),
        bidp_rsqn6: g(38),
        bidp_rsqn7: g(39),
        bidp_rsqn8: g(40),
        bidp_rsqn9: g(41),
        bidp_rsqn10: g(42),
        total_askp_rsqn: g(43),
        total_bidp_rsqn: g(44),
        ovtm_total_askp_rsqn: g(45),
        ovtm_total_bidp_rsqn: g(46),
        antc_cnpr: g(47),
        antc_cnqn: g(48),
        antc_vol: g(49),
        antc_cntg_vrss: g(50),
        antc_cntg_vrss_sign: g(51),
        antc_cntg_prdy_ctrt: g(52),
        acml_vol: g(53),
        total_askp_rsqn_icdc: g(54),
        total_bidp_rsqn_icdc: g(55),
        ovtm_total_askp_icdc: g(56),
        ovtm_total_bidp_icdc: g(57),
        stck_deal_cls_code: g(58),
        kmid_prc: g(59),
        kmid_total_rsqn: g(60),
        kmid_cls_code: g(61),
        nmid_prc: g(62),
        nmid_total_rsqn: g(63),
        nmid_cls_code: g(64),
    })
}
