//! 국내주식 실시간회원사 (통합) — WebSocket /tryitout/H0UNMBC0
//!
//! 스펙: .agent/specs/domestic_stock__realtime__h0unmbc0.md
//! 실시간 WebSocket API. 모의투자 미지원. KRX+NXT 통합.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0UNMBC0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub mksc_shrn_iscd: String,
    pub seln2_mbcr_name1: String,
    pub seln2_mbcr_name2: String,
    pub seln2_mbcr_name3: String,
    pub seln2_mbcr_name4: String,
    pub seln2_mbcr_name5: String,
    pub byov_mbcr_name1: String,
    pub byov_mbcr_name2: String,
    pub byov_mbcr_name3: String,
    pub byov_mbcr_name4: String,
    pub byov_mbcr_name5: String,
    pub total_seln_qty1: String,
    pub total_seln_qty2: String,
    pub total_seln_qty3: String,
    pub total_seln_qty4: String,
    pub total_seln_qty5: String,
    pub total_shnu_qty1: String,
    pub total_shnu_qty2: String,
    pub total_shnu_qty3: String,
    pub total_shnu_qty4: String,
    pub total_shnu_qty5: String,
    pub seln_mbcr_glob_yn_1: String,
    pub seln_mbcr_glob_yn_2: String,
    pub seln_mbcr_glob_yn_3: String,
    pub seln_mbcr_glob_yn_4: String,
    pub seln_mbcr_glob_yn_5: String,
    pub shnu_mbcr_glob_yn_1: String,
    pub shnu_mbcr_glob_yn_2: String,
    pub shnu_mbcr_glob_yn_3: String,
    pub shnu_mbcr_glob_yn_4: String,
    pub shnu_mbcr_glob_yn_5: String,
    pub seln_mbcr_no1: String,
    pub seln_mbcr_no2: String,
    pub seln_mbcr_no3: String,
    pub seln_mbcr_no4: String,
    pub seln_mbcr_no5: String,
    pub shnu_mbcr_no1: String,
    pub shnu_mbcr_no2: String,
    pub shnu_mbcr_no3: String,
    pub shnu_mbcr_no4: String,
    pub shnu_mbcr_no5: String,
    pub seln_mbcr_rlim1: String,
    pub seln_mbcr_rlim2: String,
    pub seln_mbcr_rlim3: String,
    pub seln_mbcr_rlim4: String,
    pub seln_mbcr_rlim5: String,
    pub shnu_mbcr_rlim1: String,
    pub shnu_mbcr_rlim2: String,
    pub shnu_mbcr_rlim3: String,
    pub shnu_mbcr_rlim4: String,
    pub shnu_mbcr_rlim5: String,
    pub seln_qty_icdc1: String,
    pub seln_qty_icdc2: String,
    pub seln_qty_icdc3: String,
    pub seln_qty_icdc4: String,
    pub seln_qty_icdc5: String,
    pub shnu_qty_icdc1: String,
    pub shnu_qty_icdc2: String,
    pub shnu_qty_icdc3: String,
    pub shnu_qty_icdc4: String,
    pub shnu_qty_icdc5: String,
    pub glob_total_seln_qty: String,
    pub glob_total_shnu_qty: String,
    pub glob_total_seln_qty_icdc: String,
    pub glob_total_shnu_qty_icdc: String,
    pub glob_ntby_qty: String,
    pub glob_seln_rlim: String,
    pub glob_shnu_rlim: String,
    pub seln2_mbcr_eng_name1: String,
    pub seln2_mbcr_eng_name2: String,
    pub seln2_mbcr_eng_name3: String,
    pub seln2_mbcr_eng_name4: String,
    pub seln2_mbcr_eng_name5: String,
    pub byov_mbcr_eng_name1: String,
    pub byov_mbcr_eng_name2: String,
    pub byov_mbcr_eng_name3: String,
    pub byov_mbcr_eng_name4: String,
    pub byov_mbcr_eng_name5: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 77 {
        return Err(anyhow!("필드 수 부족: {} < 77", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        mksc_shrn_iscd: g(0),
        seln2_mbcr_name1: g(1),
        seln2_mbcr_name2: g(2),
        seln2_mbcr_name3: g(3),
        seln2_mbcr_name4: g(4),
        seln2_mbcr_name5: g(5),
        byov_mbcr_name1: g(6),
        byov_mbcr_name2: g(7),
        byov_mbcr_name3: g(8),
        byov_mbcr_name4: g(9),
        byov_mbcr_name5: g(10),
        total_seln_qty1: g(11),
        total_seln_qty2: g(12),
        total_seln_qty3: g(13),
        total_seln_qty4: g(14),
        total_seln_qty5: g(15),
        total_shnu_qty1: g(16),
        total_shnu_qty2: g(17),
        total_shnu_qty3: g(18),
        total_shnu_qty4: g(19),
        total_shnu_qty5: g(20),
        seln_mbcr_glob_yn_1: g(21),
        seln_mbcr_glob_yn_2: g(22),
        seln_mbcr_glob_yn_3: g(23),
        seln_mbcr_glob_yn_4: g(24),
        seln_mbcr_glob_yn_5: g(25),
        shnu_mbcr_glob_yn_1: g(26),
        shnu_mbcr_glob_yn_2: g(27),
        shnu_mbcr_glob_yn_3: g(28),
        shnu_mbcr_glob_yn_4: g(29),
        shnu_mbcr_glob_yn_5: g(30),
        seln_mbcr_no1: g(31),
        seln_mbcr_no2: g(32),
        seln_mbcr_no3: g(33),
        seln_mbcr_no4: g(34),
        seln_mbcr_no5: g(35),
        shnu_mbcr_no1: g(36),
        shnu_mbcr_no2: g(37),
        shnu_mbcr_no3: g(38),
        shnu_mbcr_no4: g(39),
        shnu_mbcr_no5: g(40),
        seln_mbcr_rlim1: g(41),
        seln_mbcr_rlim2: g(42),
        seln_mbcr_rlim3: g(43),
        seln_mbcr_rlim4: g(44),
        seln_mbcr_rlim5: g(45),
        shnu_mbcr_rlim1: g(46),
        shnu_mbcr_rlim2: g(47),
        shnu_mbcr_rlim3: g(48),
        shnu_mbcr_rlim4: g(49),
        shnu_mbcr_rlim5: g(50),
        seln_qty_icdc1: g(51),
        seln_qty_icdc2: g(52),
        seln_qty_icdc3: g(53),
        seln_qty_icdc4: g(54),
        seln_qty_icdc5: g(55),
        shnu_qty_icdc1: g(56),
        shnu_qty_icdc2: g(57),
        shnu_qty_icdc3: g(58),
        shnu_qty_icdc4: g(59),
        shnu_qty_icdc5: g(60),
        glob_total_seln_qty: g(61),
        glob_total_shnu_qty: g(62),
        glob_total_seln_qty_icdc: g(63),
        glob_total_shnu_qty_icdc: g(64),
        glob_ntby_qty: g(65),
        glob_seln_rlim: g(66),
        glob_shnu_rlim: g(67),
        seln2_mbcr_eng_name1: g(68),
        seln2_mbcr_eng_name2: g(69),
        seln2_mbcr_eng_name3: g(70),
        seln2_mbcr_eng_name4: g(71),
        seln2_mbcr_eng_name5: g(72),
        byov_mbcr_eng_name1: g(73),
        byov_mbcr_eng_name2: g(74),
        byov_mbcr_eng_name3: g(75),
        byov_mbcr_eng_name4: g(76),
        byov_mbcr_eng_name5: if f.len() > 77 { f[77].to_string() } else { String::new() },
    })
}
