//! 국내지수 실시간프로그램매매 — WebSocket /tryitout/H0UPPGM0
//!
//! 스펙: .agent/specs/domestic_stock__realtime__h0uppgm0.md
//! 실시간 WebSocket API. 모의투자 미지원.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0UPPGM0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub bstp_cls_code: String,
    pub bsop_hour: String,
    pub arbt_seln_entm_cnqn: String,
    pub arbt_seln_onsl_cnqn: String,
    pub arbt_shnu_entm_cnqn: String,
    pub arbt_shnu_onsl_cnqn: String,
    pub nabt_seln_entm_cnqn: String,
    pub nabt_seln_onsl_cnqn: String,
    pub nabt_shnu_entm_cnqn: String,
    pub nabt_shnu_onsl_cnqn: String,
    pub arbt_seln_entm_cntg_amt: String,
    pub arbt_seln_onsl_cntg_amt: String,
    pub arbt_shnu_entm_cntg_amt: String,
    pub arbt_shnu_onsl_cntg_amt: String,
    pub nabt_seln_entm_cntg_amt: String,
    pub nabt_seln_onsl_cntg_amt: String,
    pub nabt_shnu_entm_cntg_amt: String,
    pub nabt_shnu_onsl_cntg_amt: String,
    pub arbt_smtn_seln_vol: String,
    pub arbt_smtm_seln_vol_rate: String,
    pub arbt_smtn_seln_tr_pbmn: String,
    pub arbt_smtm_seln_tr_pbmn_rate: String,
    pub arbt_smtn_shnu_vol: String,
    pub arbt_smtm_shnu_vol_rate: String,
    pub arbt_smtn_shnu_tr_pbmn: String,
    pub arbt_smtm_shnu_tr_pbmn_rate: String,
    pub arbt_smtn_ntby_qty: String,
    pub arbt_smtm_ntby_qty_rate: String,
    pub arbt_smtn_ntby_tr_pbmn: String,
    pub arbt_smtm_ntby_tr_pbmn_rate: String,
    pub nabt_smtn_seln_vol: String,
    pub nabt_smtm_seln_vol_rate: String,
    pub nabt_smtn_seln_tr_pbmn: String,
    pub nabt_smtm_seln_tr_pbmn_rate: String,
    pub nabt_smtn_shnu_vol: String,
    pub nabt_smtm_shnu_vol_rate: String,
    pub nabt_smtn_shnu_tr_pbmn: String,
    pub nabt_smtm_shnu_tr_pbmn_rate: String,
    pub nabt_smtn_ntby_qty: String,
    pub nabt_smtm_ntby_qty_rate: String,
    pub nabt_smtn_ntby_tr_pbmn: String,
    pub nabt_smtm_ntby_tr_pbmn_rate: String,
    pub whol_entm_seln_vol: String,
    pub entm_seln_vol_rate: String,
    pub whol_entm_seln_tr_pbmn: String,
    pub entm_seln_tr_pbmn_rate: String,
    pub whol_entm_shnu_vol: String,
    pub entm_shnu_vol_rate: String,
    pub whol_entm_shnu_tr_pbmn: String,
    pub entm_shnu_tr_pbmn_rate: String,
    pub whol_entm_ntby_qt: String,
    pub entm_ntby_qty_rat: String,
    pub whol_entm_ntby_tr_pbmn: String,
    pub entm_ntby_tr_pbmn_rate: String,
    pub whol_onsl_seln_vol: String,
    pub onsl_seln_vol_rate: String,
    pub whol_onsl_seln_tr_pbmn: String,
    pub onsl_seln_tr_pbmn_rate: String,
    pub whol_onsl_shnu_vol: String,
    pub onsl_shnu_vol_rate: String,
    pub whol_onsl_shnu_tr_pbmn: String,
    pub onsl_shnu_tr_pbmn_rate: String,
    pub whol_onsl_ntby_qty: String,
    pub onsl_ntby_qty_rate: String,
    pub whol_onsl_ntby_tr_pbmn: String,
    pub onsl_ntby_tr_pbmn_rate: String,
    pub total_seln_qty: String,
    pub whol_seln_vol_rate: String,
    pub total_seln_tr_pbmn: String,
    pub whol_seln_tr_pbmn_rate: String,
    pub shnu_cntg_smtn: String,
    pub whol_shun_vol_rate: String,
    pub total_shnu_tr_pbmn: String,
    pub whol_shun_tr_pbmn_rate: String,
    pub whol_ntby_qty: String,
    pub whol_smtm_ntby_qty_rate: String,
    pub whol_ntby_tr_pbmn: String,
    pub whol_ntby_tr_pbmn_rate: String,
    pub arbt_entm_ntby_qty: String,
    pub arbt_entm_ntby_tr_pbmn: String,
    pub arbt_onsl_ntby_qty: String,
    pub arbt_onsl_ntby_tr_pbmn: String,
    pub nabt_entm_ntby_qty: String,
    pub nabt_entm_ntby_tr_pbmn: String,
    pub nabt_onsl_ntby_qty: String,
    pub nabt_onsl_ntby_tr_pbmn: String,
    pub acml_vol: String,
    pub acml_tr_pbmn: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 88 {
        return Err(anyhow!("필드 수 부족: {} < 88", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        bstp_cls_code: g(0),
        bsop_hour: g(1),
        arbt_seln_entm_cnqn: g(2),
        arbt_seln_onsl_cnqn: g(3),
        arbt_shnu_entm_cnqn: g(4),
        arbt_shnu_onsl_cnqn: g(5),
        nabt_seln_entm_cnqn: g(6),
        nabt_seln_onsl_cnqn: g(7),
        nabt_shnu_entm_cnqn: g(8),
        nabt_shnu_onsl_cnqn: g(9),
        arbt_seln_entm_cntg_amt: g(10),
        arbt_seln_onsl_cntg_amt: g(11),
        arbt_shnu_entm_cntg_amt: g(12),
        arbt_shnu_onsl_cntg_amt: g(13),
        nabt_seln_entm_cntg_amt: g(14),
        nabt_seln_onsl_cntg_amt: g(15),
        nabt_shnu_entm_cntg_amt: g(16),
        nabt_shnu_onsl_cntg_amt: g(17),
        arbt_smtn_seln_vol: g(18),
        arbt_smtm_seln_vol_rate: g(19),
        arbt_smtn_seln_tr_pbmn: g(20),
        arbt_smtm_seln_tr_pbmn_rate: g(21),
        arbt_smtn_shnu_vol: g(22),
        arbt_smtm_shnu_vol_rate: g(23),
        arbt_smtn_shnu_tr_pbmn: g(24),
        arbt_smtm_shnu_tr_pbmn_rate: g(25),
        arbt_smtn_ntby_qty: g(26),
        arbt_smtm_ntby_qty_rate: g(27),
        arbt_smtn_ntby_tr_pbmn: g(28),
        arbt_smtm_ntby_tr_pbmn_rate: g(29),
        nabt_smtn_seln_vol: g(30),
        nabt_smtm_seln_vol_rate: g(31),
        nabt_smtn_seln_tr_pbmn: g(32),
        nabt_smtm_seln_tr_pbmn_rate: g(33),
        nabt_smtn_shnu_vol: g(34),
        nabt_smtm_shnu_vol_rate: g(35),
        nabt_smtn_shnu_tr_pbmn: g(36),
        nabt_smtm_shnu_tr_pbmn_rate: g(37),
        nabt_smtn_ntby_qty: g(38),
        nabt_smtm_ntby_qty_rate: g(39),
        nabt_smtn_ntby_tr_pbmn: g(40),
        nabt_smtm_ntby_tr_pbmn_rate: g(41),
        whol_entm_seln_vol: g(42),
        entm_seln_vol_rate: g(43),
        whol_entm_seln_tr_pbmn: g(44),
        entm_seln_tr_pbmn_rate: g(45),
        whol_entm_shnu_vol: g(46),
        entm_shnu_vol_rate: g(47),
        whol_entm_shnu_tr_pbmn: g(48),
        entm_shnu_tr_pbmn_rate: g(49),
        whol_entm_ntby_qt: g(50),
        entm_ntby_qty_rat: g(51),
        whol_entm_ntby_tr_pbmn: g(52),
        entm_ntby_tr_pbmn_rate: g(53),
        whol_onsl_seln_vol: g(54),
        onsl_seln_vol_rate: g(55),
        whol_onsl_seln_tr_pbmn: g(56),
        onsl_seln_tr_pbmn_rate: g(57),
        whol_onsl_shnu_vol: g(58),
        onsl_shnu_vol_rate: g(59),
        whol_onsl_shnu_tr_pbmn: g(60),
        onsl_shnu_tr_pbmn_rate: g(61),
        whol_onsl_ntby_qty: g(62),
        onsl_ntby_qty_rate: g(63),
        whol_onsl_ntby_tr_pbmn: g(64),
        onsl_ntby_tr_pbmn_rate: g(65),
        total_seln_qty: g(66),
        whol_seln_vol_rate: g(67),
        total_seln_tr_pbmn: g(68),
        whol_seln_tr_pbmn_rate: g(69),
        shnu_cntg_smtn: g(70),
        whol_shun_vol_rate: g(71),
        total_shnu_tr_pbmn: g(72),
        whol_shun_tr_pbmn_rate: g(73),
        whol_ntby_qty: g(74),
        whol_smtm_ntby_qty_rate: g(75),
        whol_ntby_tr_pbmn: g(76),
        whol_ntby_tr_pbmn_rate: g(77),
        arbt_entm_ntby_qty: g(78),
        arbt_entm_ntby_tr_pbmn: g(79),
        arbt_onsl_ntby_qty: g(80),
        arbt_onsl_ntby_tr_pbmn: g(81),
        nabt_entm_ntby_qty: g(82),
        nabt_entm_ntby_tr_pbmn: g(83),
        nabt_onsl_ntby_qty: g(84),
        nabt_onsl_ntby_tr_pbmn: g(85),
        acml_vol: g(86),
        acml_tr_pbmn: g(87),
    })
}
