//! 해외주식 실시간호가 — WebSocket /tryitout/HDFSASP0
//!
//! 스펙: .agent/specs/overseas_stock__realtime__hdfsasp0.md
//! 미국 10호가 무료 / 아시아 10호가 유료. 모의투자 미지원.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "HDFSASP0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub rsym: String,
    pub symb: String,
    pub zdiv: String,
    pub xymd: String,
    pub xhms: String,
    pub kymd: String,
    pub khms: String,
    pub bvol: String,
    pub avol: String,
    pub bdvl: String,
    pub advl: String,
    pub pbid1: String,
    pub pask1: String,
    pub vbid1: String,
    pub vask1: String,
    pub dbid1: String,
    pub dask1: String,
    pub pbid2: String,
    pub pask2: String,
    pub vbid2: String,
    pub vask2: String,
    pub dbid2: String,
    pub dask2: String,
    pub pbid3: String,
    pub pask3: String,
    pub vbid3: String,
    pub vask3: String,
    pub dbid3: String,
    pub dask3: String,
    pub pbid4: String,
    pub pask4: String,
    pub vbid4: String,
    pub vask4: String,
    pub dbid4: String,
    pub dask4: String,
    pub pbid5: String,
    pub pask5: String,
    pub vbid5: String,
    pub vask5: String,
    pub dbid5: String,
    pub dask5: String,
    pub pbid6: String,
    pub pask6: String,
    pub vbid6: String,
    pub vask6: String,
    pub dbid6: String,
    pub dask6: String,
    pub pbid7: String,
    pub pask7: String,
    pub vbid7: String,
    pub vask7: String,
    pub dbid7: String,
    pub dask7: String,
    pub pbid8: String,
    pub pask8: String,
    pub vbid8: String,
    pub vask8: String,
    pub dbid8: String,
    pub dask8: String,
    pub pbid9: String,
    pub pask9: String,
    pub vbid9: String,
    pub vask9: String,
    pub dbid9: String,
    pub dask9: String,
    pub pbid10: String,
    pub pask10: String,
    pub vbid10: String,
    pub vask10: String,
    pub dbid10: String,
    pub dask10: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 71 {
        return Err(anyhow!("필드 수 부족: {} < 71", f.len()));
    }
    let g = |i: usize| f[i].to_string();
    Ok(Response {
        rsym: g(0),
        symb: g(1),
        zdiv: g(2),
        xymd: g(3),
        xhms: g(4),
        kymd: g(5),
        khms: g(6),
        bvol: g(7),
        avol: g(8),
        bdvl: g(9),
        advl: g(10),
        pbid1: g(11),
        pask1: g(12),
        vbid1: g(13),
        vask1: g(14),
        dbid1: g(15),
        dask1: g(16),
        pbid2: g(17),
        pask2: g(18),
        vbid2: g(19),
        vask2: g(20),
        dbid2: g(21),
        dask2: g(22),
        pbid3: g(23),
        pask3: g(24),
        vbid3: g(25),
        vask3: g(26),
        dbid3: g(27),
        dask3: g(28),
        pbid4: g(29),
        pask4: g(30),
        vbid4: g(31),
        vask4: g(32),
        dbid4: g(33),
        dask4: g(34),
        pbid5: g(35),
        pask5: g(36),
        vbid5: g(37),
        vask5: g(38),
        dbid5: g(39),
        dask5: g(40),
        pbid6: g(41),
        pask6: g(42),
        vbid6: g(43),
        vask6: g(44),
        dbid6: g(45),
        dask6: g(46),
        pbid7: g(47),
        pask7: g(48),
        vbid7: g(49),
        vask7: g(50),
        dbid7: g(51),
        dask7: g(52),
        pbid8: g(53),
        pask8: g(54),
        vbid8: g(55),
        vask8: g(56),
        dbid8: g(57),
        dask8: g(58),
        pbid9: g(59),
        pask9: g(60),
        vbid9: g(61),
        vask9: g(62),
        dbid9: g(63),
        dask9: g(64),
        pbid10: g(65),
        pask10: g(66),
        vbid10: g(67),
        vask10: g(68),
        dbid10: g(69),
        dask10: g(70),
    })
}
