/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 서버 헬스체크. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입. 첫 사용자는 관리자로 생성된다. 이후 가입은 KIS_WEB_ALLOW_REGISTER 로 제어. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RegisterReq"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인. 성공 시 세션 쿠키를 발급한다. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["LoginReq"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃. 세션을 삭제하고 쿠키를 비운다. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    kisweb_session?: string;
                };
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["OkDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인된 사용자 정보 (세션 필요). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/kis-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** KIS 자격증명 등록/갱신 (암호화 저장). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["KisCredentialsReq"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["KisCredentialsStatus"];
                    };
                };
            };
        };
        post?: never;
        /** 자격증명 삭제. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["KisCredentialsStatus"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/kis-credentials/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자격증명 등록 여부 조회 (시크릿 미반환). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["KisCredentialsStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 잔고 — 국내·해외 보유종목 + 시장별 요약. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Portfolio"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 통합 포지션 — KIS 자동 보유 + 수동(매매일지 파생). 종목별 메타·비중·실현손익 포함.
         *     KIS 자격증명이 없어도 수동 포지션은 동작(현재가는 미표시).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Positions"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/meta/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 종목 관리 메타(메모·목표가·손절가·목표비중) 저장. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["MetaInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["OkDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 종목 현재가. symbol 은 국내 코드(005930) 또는 해외 티커(AAPL). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Quote"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{symbol}/spark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 미니 차트용 일봉 종가 시계열 (최근 ~30거래일, 오래된→최신). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Spark"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 종목 검색(이름·코드). symbols.db 미존재 시 빈 결과. */
        get: {
            parameters: {
                query: {
                    q: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SymbolDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 종목 마스터 강제 동기화 (공개 마스터 다운로드, 인증 불필요). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SyncResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 관심종목 목록. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["WatchlistItem"][];
                    };
                };
            };
        };
        put?: never;
        /** 관심종목 추가 (코드/티커 → 정규화 후 저장). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AddReq"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["WatchlistItem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 관심종목 삭제. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["OkDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 매매 기록 목록 (필터: symbol/side/broker/from/to). */
        get: {
            parameters: {
                query?: {
                    symbol?: string;
                    side?: string;
                    broker?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TradeDto"][];
                    };
                };
            };
        };
        put?: never;
        /** 매매 기록 추가. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["TradeInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TradeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 매매 기록 수정. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["TradeInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TradeDto"];
                    };
                };
            };
        };
        post?: never;
        /** 매매 기록 삭제. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["OkDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 매매 통계 (실현손익·승률·횟수). */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TradeStatsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddReq */
        AddReq: {
            symbol: string;
        };
        /** CurrencyAmount */
        CurrencyAmount: {
            currency: string;
            /** Format: double */
            amount: number;
        };
        /** Health */
        Health: {
            status: string;
            version: string;
        };
        /**
         * Holding
         * @description 통일된 보유 종목.
         */
        Holding: {
            market: string;
            currency: string;
            symbol: string;
            name: string;
            quantity: string;
            avg_price: string;
            current_price: string;
            eval_amount: string;
            pnl_amount: string;
            pnl_rate: string;
        };
        /** KisCredentialsReq */
        KisCredentialsReq: {
            app_key: string;
            app_secret: string;
            /** @description 계좌번호. "12345678-01" 또는 "1234567801" 형식. */
            account_number: string;
            /** @description 모의투자 계좌 여부(기본 true — 안전). */
            is_mock?: boolean;
        };
        /**
         * KisCredentialsStatus
         * @description 시크릿은 빠지고, 등록 여부·계좌·모의 여부만.
         */
        KisCredentialsStatus: {
            configured: boolean;
            account_number?: string;
            is_mock?: boolean;
        };
        /** LoginReq */
        LoginReq: {
            username: string;
            password: string;
        };
        /**
         * MetaInput
         * @description 종목 관리 메타 입력.
         */
        MetaInput: {
            memo?: string;
            /** Format: double */
            target_price?: number;
            /** Format: double */
            stop_price?: number;
            /** Format: double */
            target_weight?: number;
        };
        /**
         * OkDto
         * @description 단순 성공 응답 (여러 엔드포인트 공용 — 스키마 이름 중복 방지).
         */
        OkDto: {
            ok: boolean;
        };
        /** Portfolio */
        Portfolio: {
            is_mock: boolean;
            domestic?: components["schemas"]["Summary"];
            overseas?: components["schemas"]["Summary"];
            holdings: components["schemas"]["Holding"][];
        };
        /**
         * PositionDto
         * @description 통합 포지션 (KIS 자동 + 수동 매매일지 파생) + 관리 메타.
         */
        PositionDto: {
            source: string;
            symbol: string;
            name: string;
            market: string;
            currency: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            avg_cost: number;
            /** Format: double */
            current_price?: number;
            /** Format: double */
            eval_amount: number;
            /** Format: double */
            unrealized_pnl?: number;
            /** Format: double */
            realized_pnl: number;
            /** Format: double */
            weight: number;
            memo?: string;
            /** Format: double */
            target_price?: number;
            /** Format: double */
            stop_price?: number;
            /** Format: double */
            target_weight?: number;
        };
        /** Positions */
        Positions: {
            has_kis: boolean;
            positions: components["schemas"]["PositionDto"][];
        };
        /** Quote */
        Quote: {
            symbol: string;
            name: string;
            market: string;
            currency: string;
            price: string;
            change: string;
            change_rate: string;
            sign: string;
            open: string;
            high: string;
            low: string;
            volume: string;
        };
        /** RegisterReq */
        RegisterReq: {
            username: string;
            display_name: string;
            password: string;
        };
        /**
         * Spark
         * @description 미니 차트(스파크라인)용 종가 시계열 (오래된→최신).
         */
        Spark: {
            symbol: string;
            points: number[];
            /** @description 구간 등락 (마지막 >= 처음) */
            up: boolean;
        };
        /**
         * Summary
         * @description 시장별 요약.
         */
        Summary: {
            currency: string;
            deposit: string;
            total_eval: string;
            total_purchase: string;
            total_pnl: string;
            total_pnl_rate: string;
        };
        /** SymbolDto */
        SymbolDto: {
            code: string;
            name: string;
            name_en: string;
            kind: string;
            market_label: string;
        };
        /** SyncResult */
        SyncResult: {
            /** Format: int64 */
            synced: number;
        };
        /** TradeDto */
        TradeDto: {
            id: string;
            traded_at: string;
            symbol: string;
            name?: string;
            market?: string;
            broker?: string;
            side: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            price: number;
            /** Format: double */
            fee: number;
            currency: string;
            reason?: string;
            tags?: string;
            memo?: string;
        };
        /** TradeInput */
        TradeInput: {
            /** @description 체결일시 (RFC3339 또는 "2026-06-30"). */
            traded_at: string;
            /** @description 종목 코드/티커/이름 (KIS 해석 시도, 미해석도 허용). */
            symbol: string;
            /** @description "buy" | "sell" */
            side: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            price: number;
            /**
             * Format: double
             * @default 0
             */
            fee: number;
            broker?: string;
            currency?: string;
            reason?: string;
            tags?: string;
            memo?: string;
        };
        /** TradeStatsDto */
        TradeStatsDto: {
            /** Format: int64 */
            trade_count: number;
            /** Format: int64 */
            buy_count: number;
            /** Format: int64 */
            sell_count: number;
            /** Format: int64 */
            win_count: number;
            /** Format: double */
            win_rate: number;
            /** Format: int64 */
            symbol_count: number;
            realized: components["schemas"]["CurrencyAmount"][];
        };
        /** UserDto */
        UserDto: {
            id: string;
            username: string;
            display_name: string;
            is_admin: boolean;
        };
        /** WatchlistItem */
        WatchlistItem: {
            symbol: string;
            market: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
