//! 국내주식 실시간회원사 (KRX) — WebSocket /tryitout/H0STMBC0
//!
//! 스펙: .agent/specs/domestic_stock__realtime__h0stmbc0.md
//! 실시간 WebSocket API. 모의투자 미지원.

use anyhow::{anyhow, Result};
use serde::Deserialize;

pub const TR_ID: &str = "H0STMBC0";

pub fn subscribe_payload(approval_key: &str, custtype: &str, tr_type: &str, tr_key: &str) -> serde_json::Value {
    serde_json::json!({
        "header": {
            "approval_key": approval_key,
            "custtype": custtype,
            "tr_type": tr_type,
            "content-type": "utf-8",
        },
        "body": {
            "input": {
                "tr_id": TR_ID,
                "tr_key": tr_key,
            },
        },
    })
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Response {
    pub mksc_shrn_iscd: String,
    pub seln2_mbcr_name1: String,
    pub seln2_mbcr_name2: String,
    pub seln2_mbcr_name3: String,
    pub seln2_mbcr_name4: String,
    pub seln2_mbcr_name5: String,
    pub byov_mbcr_name1: String,
    pub byov_mbcr_name2: String,
    pub byov_mbcr_name3: String,
    pub byov_mbcr_name4: String,
    pub byov_mbcr_name5: String,
    pub total_seln_qty1: String,
    pub total_seln_qty2: String,
    pub total_seln_qty3: String,
    pub total_seln_qty4: String,
    pub total_seln_qty5: String,
    pub total_shnu_qty1: String,
    pub total_shnu_qty2: String,
    pub total_shnu_qty3: String,
    pub total_shnu_qty4: String,
    pub total_shnu_qty5: String,
    pub seln_mbcr_glob_yn_1: String,
    pub seln_mbcr_glob_yn_2: String,
    pub seln_mbcr_glob_yn_3: String,
    pub seln_mbcr_glob_yn_4: String,
    pub seln_mbcr_glob_yn_5: String,
    pub shnu_mbcr_glob_yn_1: String,
    pub shnu_mbcr_glob_yn_2: String,
    pub shnu_mbcr_glob_yn_3: String,
    pub shnu_mbcr_glob_yn_4: String,
    pub shnu_mbcr_glob_yn_5: String,
    pub seln_mbcr_no1: String,
    pub seln_mbcr_no2: String,
    pub seln_mbcr_no3: String,
    pub seln_mbcr_no4: String,
    pub seln_mbcr_no5: String,
    pub shnu_mbcr_no1: String,
    pub shnu_mbcr_no2: String,
    pub shnu_mbcr_no3: String,
    pub shnu_mbcr_no4: String,
    pub shnu_mbcr_no5: String,
    pub seln_mbcr_rlim1: String,
    pub seln_mbcr_rlim2: String,
    pub seln_mbcr_rlim3: String,
    pub seln_mbcr_rlim4: String,
    pub seln_mbcr_rlim5: String,
    pub shnu_mbcr_rlim1: String,
    pub shnu_mbcr_rlim2: String,
    pub shnu_mbcr_rlim3: String,
    pub shnu_mbcr_rlim4: String,
    pub shnu_mbcr_rlim5: String,
    pub seln_qty_icdc1: String,
    pub seln_qty_icdc2: String,
    pub seln_qty_icdc3: String,
    pub seln_qty_icdc4: String,
    pub seln_qty_icdc5: String,
    pub shnu_qty_icdc1: String,
    pub shnu_qty_icdc2: String,
    pub shnu_qty_icdc3: String,
    pub shnu_qty_icdc4: String,
    pub shnu_qty_icdc5: String,
    pub glob_total_seln_qty: String,
    pub glob_total_shnu_qty: String,
    pub glob_total_seln_qty_icdc: String,
    pub glob_total_shnu_qty_icdc: String,
    pub glob_ntby_qty: String,
    pub glob_seln_rlim: String,
    pub glob_shnu_rlim: String,
    pub seln2_mbcr_eng_name1: String,
    pub seln2_mbcr_eng_name2: String,
    pub seln2_mbcr_eng_name3: String,
    pub seln2_mbcr_eng_name4: String,
    pub seln2_mbcr_eng_name5: String,
    pub byov_mbcr_eng_name1: String,
    pub byov_mbcr_eng_name2: String,
    pub byov_mbcr_eng_name3: String,
    pub byov_mbcr_eng_name4: String,
    pub byov_mbcr_eng_name5: String,
}

pub fn parse_frame(data: &str) -> Result<Response> {
    let f: Vec<&str> = data.split('^').collect();
    if f.len() < 77 {
        return Err(anyhow!("필드 수 부족: {} < 77", f.len()));
    }
    Ok(Response {
        mksc_shrn_iscd: f[0].to_string(),
        seln2_mbcr_name1: f[1].to_string(),
        seln2_mbcr_name2: f[2].to_string(),
        seln2_mbcr_name3: f[3].to_string(),
        seln2_mbcr_name4: f[4].to_string(),
        seln2_mbcr_name5: f[5].to_string(),
        byov_mbcr_name1: f[6].to_string(),
        byov_mbcr_name2: f[7].to_string(),
        byov_mbcr_name3: f[8].to_string(),
        byov_mbcr_name4: f[9].to_string(),
        byov_mbcr_name5: f[10].to_string(),
        total_seln_qty1: f[11].to_string(),
        total_seln_qty2: f[12].to_string(),
        total_seln_qty3: f[13].to_string(),
        total_seln_qty4: f[14].to_string(),
        total_seln_qty5: f[15].to_string(),
        total_shnu_qty1: f[16].to_string(),
        total_shnu_qty2: f[17].to_string(),
        total_shnu_qty3: f[18].to_string(),
        total_shnu_qty4: f[19].to_string(),
        total_shnu_qty5: f[20].to_string(),
        seln_mbcr_glob_yn_1: f[21].to_string(),
        seln_mbcr_glob_yn_2: f[22].to_string(),
        seln_mbcr_glob_yn_3: f[23].to_string(),
        seln_mbcr_glob_yn_4: f[24].to_string(),
        seln_mbcr_glob_yn_5: f[25].to_string(),
        shnu_mbcr_glob_yn_1: f[26].to_string(),
        shnu_mbcr_glob_yn_2: f[27].to_string(),
        shnu_mbcr_glob_yn_3: f[28].to_string(),
        shnu_mbcr_glob_yn_4: f[29].to_string(),
        shnu_mbcr_glob_yn_5: f[30].to_string(),
        seln_mbcr_no1: f[31].to_string(),
        seln_mbcr_no2: f[32].to_string(),
        seln_mbcr_no3: f[33].to_string(),
        seln_mbcr_no4: f[34].to_string(),
        seln_mbcr_no5: f[35].to_string(),
        shnu_mbcr_no1: f[36].to_string(),
        shnu_mbcr_no2: f[37].to_string(),
        shnu_mbcr_no3: f[38].to_string(),
        shnu_mbcr_no4: f[39].to_string(),
        shnu_mbcr_no5: f[40].to_string(),
        seln_mbcr_rlim1: f[41].to_string(),
        seln_mbcr_rlim2: f[42].to_string(),
        seln_mbcr_rlim3: f[43].to_string(),
        seln_mbcr_rlim4: f[44].to_string(),
        seln_mbcr_rlim5: f[45].to_string(),
        shnu_mbcr_rlim1: f[46].to_string(),
        shnu_mbcr_rlim2: f[47].to_string(),
        shnu_mbcr_rlim3: f[48].to_string(),
        shnu_mbcr_rlim4: f[49].to_string(),
        shnu_mbcr_rlim5: f[50].to_string(),
        seln_qty_icdc1: f[51].to_string(),
        seln_qty_icdc2: f[52].to_string(),
        seln_qty_icdc3: f[53].to_string(),
        seln_qty_icdc4: f[54].to_string(),
        seln_qty_icdc5: f[55].to_string(),
        shnu_qty_icdc1: f[56].to_string(),
        shnu_qty_icdc2: f[57].to_string(),
        shnu_qty_icdc3: f[58].to_string(),
        shnu_qty_icdc4: f[59].to_string(),
        shnu_qty_icdc5: f[60].to_string(),
        glob_total_seln_qty: f[61].to_string(),
        glob_total_shnu_qty: f[62].to_string(),
        glob_total_seln_qty_icdc: f[63].to_string(),
        glob_total_shnu_qty_icdc: f[64].to_string(),
        glob_ntby_qty: f[65].to_string(),
        glob_seln_rlim: f[66].to_string(),
        glob_shnu_rlim: f[67].to_string(),
        seln2_mbcr_eng_name1: f[68].to_string(),
        seln2_mbcr_eng_name2: f[69].to_string(),
        seln2_mbcr_eng_name3: f[70].to_string(),
        seln2_mbcr_eng_name4: f[71].to_string(),
        seln2_mbcr_eng_name5: f[72].to_string(),
        byov_mbcr_eng_name1: f[73].to_string(),
        byov_mbcr_eng_name2: f[74].to_string(),
        byov_mbcr_eng_name3: f[75].to_string(),
        byov_mbcr_eng_name4: f[76].to_string(),
        byov_mbcr_eng_name5: if f.len() > 77 { f[77].to_string() } else { String::new() },
    })
}
